name: famity
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI and utilities
  cupertino_icons: ^1.0.8
  glassmorphism: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  

  flutter_launcher_icons: ^0.14.1




  # Media and storage
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  video_player: ^2.8.6
  
  just_audio: ^0.9.38
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2

  # Permissions, sharing, network
  permission_handler: ^11.3.1
  share_plus: ^7.2.1
  dio: ^5.4.0
  http: ^1.2.1

  # Firebase & notifications
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.2
  onesignal_flutter: ^5.1.3
  


  # Supabase
  supabase_flutter: ^2.6.0

  # Auth & utils
  google_sign_in: ^6.2.1
  uuid: ^4.4.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/thirdimage.png
    - assets/images/firstimage.png
    - assets/images/google.png
    - assets/images/secondimage.png
    - assets/images/logo.png
    - assets/images/fifthimage.png
    - assets/animations/family_loading.json
    - assets/animations/loader.json
    - assets/icon/icon.jpg
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"
  adaptive_icon_background: "#EBD6FB"
  adaptive_icon_foreground: "assets/icon/icon.jpg"




